replicaCount: 1

image: barkend/alarm-launcher
imageConfig:
  pullPolicy: IfNotPresent

nameOverride: "alarm-launcher"
fullnameOverride: "alarm-launcher"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

kafka:
  servers: barkend-kafka-bootstrap.kafka:9092

alarm:
  endpoint: http://sonoff.localnet/api/relay
  apikey:
  duration: 5s