spring:
  application:
    name: alarm-launcher

  kafka:
    bootstrap-servers:
    consumer:
      group-id: alarm-launcher
      auto-offset-reset: latest
      enable-auto-commit: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

application:
  alarm:
    endpoint:
    api-key:
    duration: 5s
    silence-time-start: '23:30'
    silence-time-end: '07:30'