apiVersion: v1
kind: ConfigMap
metadata:
  name: alarm-launcher-config
  labels:
    {{- include "alarm-launcher.labels" . | nindent 4 }}
data:
  logback-spring.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>
      <springProperty scope="context" name="application_name" source="spring.application.name"/>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
      <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
      </pattern>
      </encoder>
      </appender>
      <root level="INFO">
      <appender-ref ref="STDOUT"/>
      </root>
      </configuration>