apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "alarm-launcher.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "alarm-launcher.name" . }}
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75