apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "alarm-launcher.fullname" . }}-secret
  labels:
    {{- include "alarm-launcher.labels" . | nindent 4 }}
spec:
  encryptedData:
    apikey: {{ .Values.alarm.apikey }}