apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "alarm-launcher.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "alarm-launcher.name" . }}
    helm.sh/chart: {{ include "alarm-launcher.chart" . }}
spec:
  encryptedData:
    apikey: {{ .Values.alarm.apikey }}