apiVersion: v1
kind: Service
metadata:
  name: {{ include "alarm-launcher.fullname" . }}
  labels:
    {{- include "alarm-launcher.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alarm-launcher.selectorLabels" . | nindent 4 }}