apiVersion: v1
kind: Service
metadata:
  name: {{ include "ml-serving.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ml-serving.name" . }}
    helm.sh/chart: {{ include "ml-serving.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "ml-serving.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port.rest }}
      targetPort: rest
      protocol: TCP
      name: rest
    - port: {{ .Values.service.port.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "ml-serving.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
