apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bark-detector.fullname" . }}-config
  labels:
    {{- include "bark-detector.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "config/*").AsConfig | indent 2 }}