apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "bark-detector.name" . }}
  labels:
    {{- include "bark-detector.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "bark-detector.name" . }}
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 75