apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bark-detector.fullname" . }}-secret
  labels:
    app: {{ include "bark-detector.name" . }}
    helm.sh/chart: {{ include "bark-detector.chart" . }}
spec:
  encryptedData:
    s3.password: {{ .Values.s3.password }}