apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ include "bark-detector.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "bark-detector.name" . }}
    helm.sh/chart: {{ include "bark-detector.chart" . }}
spec:
  encryptedData:
    s3.password: {{ .Values.s3.password }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: {{ include "bark-detector.fullname" . }}-secret
      namespace: {{ .Release.Namespace }}