apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "bark-detector.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bark-detector.labels" . | nindent 4 }}
spec:
  encryptedData:
    s3.password: {{ required "S3 password not found" .Values.s3.password }}