apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bark-detector.fullname" . }}-secret
  labels:
    app: {{ include "bark-detector.name" . }}
    helm.sh/chart: {{ include "bark-detector.chart" . }}
type: Opaque
data:
  s3.password: {{ .Values.s3.password | b64enc | quote }}