---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barkend-bark-detector
  namespace: argocd
spec:
  destination:
    namespace: barkend
    server: https://kubernetes.default.svc
  project: barkend
  source:
    helm:
      parameters:
       - name: build.enabled
         value: "false"
       - name: deploy.route.tls.enabled
         value: "true"
       - name: image.name
         value: quay.io/ablock/gitops-helm-quarkus
    path: barkend-alarm-launcher/charts/alarm-launcher
    repoURL: https://github.com/santiagocardin/barkend.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true