replicaCount: 1

image: barkend/ml-serving
imageConfig:
  pullPolicy: IfNotPresent

nameOverride: "ml-serving"
fullnameOverride: "ml-serving"

service:
  type: ClusterIP
  port:
    rest: 9000
    grpc: 5000

resources:
  limits:
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi

s3:
  endpoint: https://192.168.1.14:443
  user: admin
  password: