name: CI alarm-launcher
on:
  push:
    paths:
      - "barkend-alarm-launcher/**"
      - ".github/workflows/alarm-launcher.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: registry-1.docker.io
          server-username: DOCKER_USERNAME
          server-password: DOCKER_PASSWORD #pragma: allowlist secret

      - name: Build with Maven
        run: mvn -f barkend-alarm-launcher clean package
      - name: Push image to registry
        run: mvn -f barkend-alarm-launcher jib:build
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}